global:
  resolve_timeout: 1m
  slack_api_url: https://hooks.slack.com/services/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

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerting'
    send_resolved: true





