global:
  resolve_timeout: 1m
  slack_api_url: https://hooks.slack.com/services/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

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    #  send_resolved: true





