route:
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
    - send_resolved: true
      channel: "#general"
      api_url: https://slack.com/api/chat.postMessage
      http_config:
        authorization:
          credentials: xoxb-2857315046340-2981209061634-4hXYxjpUUa8LgcAZGVfIj57w